# This is an example file name. Yours will have a random string of characters.
# Find the `builddeploy` step and add the `pre_deployment_command` line.

# ... (top of the file remains the same)

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
          # ADD THIS LINE:
          pre_deployment_command: "npm install --legacy-peer-deps"
# ... (rest of the file remains the same)
